In [31]:
import numpy as np

lista = [1,2,3]
array = np.array(lista)


In [32]:
array

array([1, 2, 3])

In [33]:
array[1]

np.int64(2)

In [34]:
np.arange(5,30,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [35]:
np.zeros(shape=(10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [36]:
np.ones(shape=(5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
aleatorios = np.random.randint(0,100,50)
print(aleatorios)

[10 68 97 91 18 51 63 30 24 39 96  7 78 38 63 10 11 79 42  2 78 22 42  5
 62 26 42 24  2 82 18 55  4 23 51 20 87 62 58 23  8 38 23 74 51 36 99 93
 17 98]


In [38]:
aleatorios.argmax()

np.int64(46)

In [39]:
aleatorios.max()

np.int32(99)

In [40]:
aleatorios.min()

np.int32(2)

In [41]:
aleatorios.argmin()

np.int64(19)

In [43]:
aleatorios = aleatorios.reshape(10,5)
aleatorios

array([[10, 68, 97, 91, 18],
       [51, 63, 30, 24, 39],
       [96,  7, 78, 38, 63],
       [10, 11, 79, 42,  2],
       [78, 22, 42,  5, 62],
       [26, 42, 24,  2, 82],
       [18, 55,  4, 23, 51],
       [20, 87, 62, 58, 23],
       [ 8, 38, 23, 74, 51],
       [36, 99, 93, 17, 98]], dtype=int32)

In [50]:
aleatorios[0,1]

np.int32(68)