In [14]:
import numpy as np

def generar_matriz_aleatoria(num_elementos, dimensiones):
    """
    Genera un array de números aleatorios enteros entre 1 y 100 y lo redimensiona a las dimensiones especificadas.
    
    Parámetros:
        num_elementos (int): Número total de elementos aleatorios a generar. Ejemplo: 50
        dimensiones (tuple): Dimensiones a las que se debe redimensionar el array. Ejemplo (5,10)
    
    Retorna:
        numpy.ndarray: La matriz redimensionada si el número de elementos es compatible con las dimensiones especificadas.
        str: Mensaje de error si el redimensionamiento no es posible.
    
    """    

    dimensiona = dimensiones[0]
    dimensionb = dimensiones[1]

    # Tambien se puede usar el metodo np.prod(tupla)
    if num_elementos != dimensiona * dimensionb:
        #print("Dimensionado no es posible")
        arrglo_aleatorio = "Dimensionado no es posible"
    else:
        arrglo_aleatorio = np.random.randint(1, 100, num_elementos)
        arrglo_aleatorio = arrglo_aleatorio.reshape(dimensiones)

    return arrglo_aleatorio

arreglo = generar_matriz_aleatoria(50,(5,10))
print(arreglo)

[[16 69 48 83 43  1 87 56  2 39]
 [65 80 62 15  7 38 66 71 89 38]
 [97 96 29 87 57 83 23 41 71 80]
 [60 64 21 51 79  4 24 66 87 73]
 [70 66  4 10  7 62 27 92 80 73]]
