In [2]:
###################Ejercicio
#Crear la funcion "pares" que devuelve un array de números pares entre dos valores pasados como parametros a la funcion (inicio y fin)
#Utilizar la funcion "pares" con los numeros 1 y 30
#Utilizar la funcion "pares" con los numeros 2 y 40

In [3]:
import numpy as np
def pares(inicio, fin):
    if(inicio % 2 == 0):
        array = np.arange(inicio,fin,2)
    else:
        inicio = inicio + 1
        array = np.arange(inicio,fin,2)
    return array

#Probamos el metodo
print(pares(1,30))
print(pares(2,40))

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [4]:
###################Ejercicio
#1.Crear una lista con numeros del 10 al 19
#2.Crear otra lista con numeros del 50 al 59
#3.Crear una matriz 2x10 con la lista anteriores
#4.Crear otra matriz que cuyos valores sean iguales a la matriz anterior multiplicados por 2

In [11]:
import numpy as np
lista1 = np.arange(10,20)
lista2 = np.arange(50,60)
suma_lista = (lista1,lista2)
print(suma_lista)
array_doble = np.array(suma_lista)
array_resultado = (array_doble * 2)
print(array_resultado) 

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]), array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59]))
[[ 20  22  24  26  28  30  32  34  36  38]
 [100 102 104 106 108 110 112 114 116 118]]


In [6]:
###################Ejercicio
#Crear una lista con los valores numericos del 0 al 30
#Crear otra lista con los primeros 10 valores de lista inicial
#Crear otra lista con los últimos 10 valores de lista inicial
#Crear un bucle que recorra esta última lista de valores finales

In [2]:
import numpy as np
lista1 = np.arange(0,30)
lista2 = lista1[0:10]
lista3 = lista1[-10:]
for numero in lista3:
    print(numero)

20
21
22
23
24
25
26
27
28
29
